from enum import Enum


class WorkflowState(str, Enum):
    """Strongly-typed states of the Master AI Orchestration Engine."""
    DISCOVERED = "DISCOVERED"
    PROCESSING = "PROCESSING"
    ANALYZED = "ANALYZED"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    AUTOMATION_RUNNING = "AUTOMATION_RUNNING"
    WAITING_FOR_MANUAL_ACTION = "WAITING_FOR_MANUAL_ACTION"
    RESUMED = "RESUMED"
    SUBMITTED = "SUBMITTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class UserDecision(str, Enum):
    """User decision actions upon receiving interactive Telegram / platform alert."""
    IGNORE = "IGNORE"
    REMIND = "REMIND"
    APPLY = "APPLY"


class WorkflowStep(str, Enum):
    """Granular execution steps in the Government Job application pipeline."""
    JOB_DISCOVERED = "JOB_DISCOVERED"
    DUPLICATE_DETECTION = "DUPLICATE_DETECTION"
    DOWNLOAD_NOTIFICATION = "DOWNLOAD_NOTIFICATION"
    EXTRACT_NOTIFICATION = "EXTRACT_NOTIFICATION"
    VALIDATE_JSON = "VALIDATE_JSON"
    ELIGIBILITY_CHECK = "ELIGIBILITY_CHECK"
    GENERATE_SUMMARY = "GENERATE_SUMMARY"
    TELEGRAM_MESSAGE = "TELEGRAM_MESSAGE"
    WAIT_USER_DECISION = "WAIT_USER_DECISION"

    # Browser Automation Steps
    AUTOMATION_START = "AUTOMATION_START"
    AUTOMATION_LOGIN = "AUTOMATION_LOGIN"
    AUTOMATION_PROFILE = "AUTOMATION_PROFILE"
    AUTOMATION_EDUCATION = "AUTOMATION_EDUCATION"
    AUTOMATION_EXPERIENCE = "AUTOMATION_EXPERIENCE"
    AUTOMATION_DOCUMENTS = "AUTOMATION_DOCUMENTS"
    AUTOMATION_REVIEW = "AUTOMATION_REVIEW"
    AUTOMATION_MANUAL_PAUSE = "AUTOMATION_MANUAL_PAUSE"
    AUTOMATION_RESUME = "AUTOMATION_RESUME"
    AUTOMATION_SUBMIT = "AUTOMATION_SUBMIT"
    DOWNLOAD_RECEIPT = "DOWNLOAD_RECEIPT"
    SAVE_APPLICATION_NUMBER = "SAVE_APPLICATION_NUMBER"
    NOTIFY_USER = "NOTIFY_USER"
    COMPLETE_WORKFLOW = "COMPLETE_WORKFLOW"
